# Generated by Django 4.2.20 on 2025-04-11 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('course_number', models.CharField(max_length=50)),
                ('professor', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('meeting_dates', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=20)),
                ('meeting_times', models.TimeField()),
                ('end_date', models.DateField()),
                ('class_type', models.CharField(choices=[('In-Class', 'In-Class'), ('Virtual', 'Virtual'), ('Mixed', 'Mixed')], max_length=50)),
            ],
        ),
    ]
