# Generated by Django 3.2.25 on 2025-04-29 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchedulingSurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('year', models.CharField(choices=[('FR', 'Freshman'), ('SO', 'Sophomore'), ('JR', 'Junior'), ('SR', 'Senior'), ('GR', 'Graduate')], max_length=2)),
                ('major', models.CharField(max_length=100)),
                ('minor', models.CharField(blank=True, max_length=100, null=True)),
                ('special_programs', models.CharField(blank=True, max_length=200, null=True)),
                ('preferred_times', models.CharField(max_length=200)),
                ('preferred_days', models.CharField(max_length=200)),
                ('days_off', models.CharField(blank=True, max_length=200)),
                ('class_spacing', models.CharField(max_length=50)),
                ('learning_style', models.CharField(max_length=50)),
                ('format_preference', models.CharField(max_length=50)),
                ('professor_notes', models.TextField(blank=True)),
                ('must_have_courses', models.TextField(blank=True)),
                ('work_schedule', models.TextField(blank=True)),
                ('other_commitments', models.TextField(blank=True)),
                ('commute_time', models.CharField(blank=True, max_length=100)),
                ('academic_interests', models.TextField()),
                ('career_goals', models.TextField(blank=True)),
                ('elective_interests', models.TextField(blank=True)),
                ('preferred_distribution', models.CharField(max_length=50)),
                ('max_classes_per_day', models.IntegerField()),
                ('min_gap_minutes', models.IntegerField()),
                ('clustered_or_spread', models.CharField(max_length=50)),
                ('heavy_load_preference', models.BooleanField(default=False)),
                ('night_classes_ok', models.BooleanField(default=False)),
                ('other_notes', models.TextField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='course',
            name='class_type',
        ),
        migrations.RemoveField(
            model_name='course',
            name='course_number',
        ),
        migrations.RemoveField(
            model_name='course',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='course',
            name='meeting_dates',
        ),
        migrations.RemoveField(
            model_name='course',
            name='meeting_times',
        ),
        migrations.RemoveField(
            model_name='course',
            name='professor',
        ),
        migrations.RemoveField(
            model_name='course',
            name='start_date',
        ),
        migrations.AddField(
            model_name='course',
            name='code',
            field=models.CharField(default='UNKN', max_length=20),
        ),
        migrations.AddField(
            model_name='course',
            name='corerequistes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='course',
            name='credits',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='course',
            name='crossListed',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.TextField(default='UNKN'),
        ),
        migrations.AddField(
            model_name='course',
            name='prerequisites',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_id', models.CharField(max_length=10)),
                ('instructor', models.CharField(max_length=100)),
                ('days', models.CharField(max_length=10)),
                ('time', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=100)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.course')),
            ],
        ),
    ]
