# Generated by Django 3.2.25 on 2025-04-29 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20250429_1233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='corerequistes',
        ),
        migrations.RemoveField(
            model_name='course',
            name='crossListed',
        ),
        migrations.RemoveField(
            model_name='course',
            name='title',
        ),
        migrations.RemoveField(
            model_name='section',
            name='days',
        ),
        migrations.RemoveField(
            model_name='section',
            name='instructor',
        ),
        migrations.RemoveField(
            model_name='section',
            name='location',
        ),
        migrations.RemoveField(
            model_name='section',
            name='section_id',
        ),
        migrations.RemoveField(
            model_name='section',
            name='time',
        ),
        migrations.AddField(
            model_name='course',
            name='corequisites',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='course',
            name='crosslisted_courses',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='course',
            name='name',
            field=models.CharField(default='Untitled Course', max_length=200),
        ),
        migrations.AddField(
            model_name='section',
            name='begins',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='building',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='section',
            name='campus',
            field=models.CharField(blank=True, default='Main', max_length=100),
        ),
        migrations.AddField(
            model_name='section',
            name='college',
            field=models.CharField(blank=True, default='Undeclared', max_length=100),
        ),
        migrations.AddField(
            model_name='section',
            name='crn',
            field=models.CharField(default='00000', max_length=10),
        ),
        migrations.AddField(
            model_name='section',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='ends',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='fr',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='section',
            name='instructional_method',
            field=models.CharField(blank=True, default='Standard', max_length=100),
        ),
        migrations.AddField(
            model_name='section',
            name='instructor_first_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='section',
            name='instructor_last_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='section',
            name='mo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='section',
            name='mode',
            field=models.CharField(blank=True, default='In-Person', max_length=100),
        ),
        migrations.AddField(
            model_name='section',
            name='room',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='section',
            name='sa',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='section',
            name='section_code',
            field=models.CharField(default='A', max_length=10),
        ),
        migrations.AddField(
            model_name='section',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='su',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='section',
            name='term',
            field=models.CharField(default='TBD', max_length=20),
        ),
        migrations.AddField(
            model_name='section',
            name='th',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='section',
            name='tu',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='section',
            name='we',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='course',
            name='credits',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True, default='No description provided.'),
        ),
        migrations.AlterField(
            model_name='course',
            name='prerequisites',
            field=models.TextField(blank=True, default=''),
        ),
    ]
