# Generated by Django 4.2.20 on 2025-05-03 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedulingsurvey',
            name='preferred_distribution',
            field=models.CharField(choices=[('MWF', 'Monday/Wednesday/Friday'), ('TTH', 'Tuesday/Thursday'), ('Spread', 'Spread Across Week')], default='Spread', max_length=50),
        ),
    ]
