# Generated by Django 4.2.20 on 2025-05-03 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_schedulingsurvey_preferred_distribution'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulingsurvey',
            name='time_distribution',
            field=models.CharField(choices=[('morning', 'Morning-heavy'), ('afternoon', 'Afternoon-heavy'), ('even', 'Evenly distributed')], default='even', max_length=50),
        ),
    ]
