# Generated by Django 4.2.20 on 2025-05-04 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_profile_additional_info_profile_survey_results_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedulingsurvey',
            name='max_classes_per_day',
        ),
        migrations.RemoveField(
            model_name='schedulingsurvey',
            name='min_gap_minutes',
        ),
    ]
