# Generated by Django 4.2.20 on 2025-05-04 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_remove_schedulingsurvey_max_classes_per_day_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='building',
        ),
        migrations.RemoveField(
            model_name='section',
            name='campus',
        ),
        migrations.RemoveField(
            model_name='section',
            name='college',
        ),
        migrations.RemoveField(
            model_name='section',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='section',
            name='instructional_method',
        ),
        migrations.RemoveField(
            model_name='section',
            name='instructor_first_name',
        ),
        migrations.RemoveField(
            model_name='section',
            name='instructor_last_name',
        ),
        migrations.RemoveField(
            model_name='section',
            name='mode',
        ),
        migrations.RemoveField(
            model_name='section',
            name='room',
        ),
        migrations.RemoveField(
            model_name='section',
            name='start_date',
        ),
        migrations.AddField(
            model_name='section',
            name='course_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='course_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='subject',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
