# Generated by Django 4.2.20 on 2025-05-07 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_schedulingsurvey_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='building',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='instructional_method',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='instructor_first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='instructor_last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='mode',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='room',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
